import Gathering from './gatheringclass'

export const Gatherings: Gathering[] = [
  {
    id: 'c1',
    period: '9/20~9/27',
    title: '오사카 가실분',
    content:
      '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 1),
    location: '일본 오사카',
  },
  {
    id: 'c2',
    period: '9/20~9/25',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 2),
    location: '일본 오사카',
  },
  {
    id: 'c3',
    period: '9/20~9/26',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 5),
    location: '일본 오사카',
  },
  {
    id: 'c4',
    period: '9/20~9/28',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 6),
    location: '일본 오사카',
  },
  {
    id: 'c5',
    period: '9/20~9/29',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 7),
    location: '일본 오사카',
  },
  {
    id: 'c6',
    period: '9/20~9/22',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 3),
    location: '일본 오사카',
  },
  {
    id: 'c7',
    period: '9/20~9/23',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 2),
    location: '일본 오사카',
  },
  {
    id: 'c8',
    period: '9/20~9/24',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 1),
    location: '일본 오사카',
  },
  {
    id: 'c9',
    period: '9/20~9/25',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 2),
    location: '일본 오사카',
  },
  {
    id: 'c10',
    period: '9/20~9/27',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 4),
    location: '일본 오사카',
  },
  {
    id: 'c11',
    period: '9/20~9/21',
    title: '오사카 가실분',
    content: '오사카 갈사람 오사카 갈사람 오사카 갈사람 ㅎㅎ',
    author: '홍길동',
    commentCnt: 3,
    registerDate: new Date(2024, 8, 5),
    location: '일본 오사카',
  },
]
